### PR TITLE
Be possible style props

### PR DESCRIPTION
**Pull request by Kikobeats**
I don't know why in the codebase you restrict `background-color` as unique style to apply.

For my case of use, I use this modification and works fine. Now I can add border style and more stuff.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Maybe this line is related:

https://github.com/yuku-t/jquery-overlay/blob/master/jquery.overlay.js#L113

but really I don't know, please give me feedback 😄

**Comment by yuku-t** [comment]
> why in the codebase you restrict background-color as unique style to apply.

To answer the question, I need to explain how this plugin works.

To emphasize particular words in textarea, this plugin creates a div element and modifies the element's style to fit to the words, then it moves the element **under** the textarea. (I really regret that I named this plugin as jquery-**overlay**.) This means that this plugin cannot modify styles of textarea.

So, I didn't intend to restrict `background-color` as unique style to apply, but I intended to reject styles that don't work as expected. For example, if the plugin accepts `color: red`, beginners may expect the matching words to be red, but it doesn't work.

It is ok to allow `border` style because it works. However, I want to maintain allowed styles in whitelist format.

**Comment by Kikobeats** [comment]
Now I understand your code 😄 

However, I feel that my solution is simple and effective: you don't need to maintain a list of allowed css properties (more plugin size, more plugin control, less extensible... also this approach need and exhaustive list of allowed css properties). Simply you can delegate in the user configuration.

I'm sure that adding your comment in the README could be useful to know what or not do with the plugin.

**Comment by yuku-t** [comment]
It seems that your opinion makes sense. Thanks for your contribution :+1:

**Comment by Kikobeats** [comment]
@yuku-t thanks! I'm working with your plugin, so I hope make more PR for improve it 😄

**Comment by Kikobeats** [comment]
@yuku-t btw do you check if https://github.com/yuku-t/jquery-overlay/blob/master/jquery.overlay.js#L113 is related? I don't know

**Comment by yuku-t** [comment]
It is not related to this PR.

As I mentioned, the created div is put under the textarea. To make the div be visible, this plugin changes the textarea's `background-color` style to `transparent`. In addition, it also adds another layer under the textarea to emulate the original `background-color`. This line tells what style should be copied from the textarea to the layer.

**Comment by yuku-t** [comment]
> As I mentioned, the created div is put under the textarea.

Sorry, it's a lie :sweat_smile:
Plugin creates a span element for each matching strings.

image

**Pull request merged**
